# @package _global_
# Defaults for training for the BlockPush_v0 dataset.

seed: 100000
dataset_repo_id: jclinton1/blockpush

training:
  offline_steps: 400000 # 1500 * 114000/64
  online_steps: 0
  eval_freq: 5000
  save_freq: 5000
  save_checkpoint: true
  batch_size: 64
  grad_clip_norm: 10
  lr: 1.0e-4
  lr_scheduler: cosine
  lr_warmup_steps: 500
  adam_betas: [0.95, 0.999]
  adam_eps: 1.0e-8
  adam_weight_decay: 1.0e-6
  online_steps_between_rollouts: 1

  # VQ-BeT specific
  vqvae_lr: 1.0e-3
  n_vqvae_training_steps: 20000
  bet_weight_decay: 2e-4
  bet_learning_rate: 5.5e-5
  bet_betas: [ 0.9, 0.999 ]

  delta_timestamps:
    observation.state: "[i / ${fps} for i in range(1 - ${policy.n_obs_steps}, 1)]"
    observation.environment_state: "[i / ${fps} for i in range(1 - ${policy.n_obs_steps}, 1)]"
    action: "[i / ${fps} for i in range(1 - ${policy.n_obs_steps}, ${policy.n_action_pred_token} + ${policy.action_chunk_size} - 1)]"

eval:
  n_episodes: 50
  batch_size: 50

policy:
  name: vqbet
  # Input / output structure.
  n_obs_steps: 3
  n_action_pred_token: 1
  action_chunk_size: 1
  input_shapes:
    observation.state: ["${env.state_dim}"]
    observation.environment_state: [12]
  output_shapes:
    action: [2]

  # Normalization / Unnormalization
  input_normalization_modes:
    observation.state: min_max
    observation.environment_state: min_max
  output_normalization_modes:
    action: min_max

  # Architecture / modeling.

  # VQ-VAE
  n_vqvae_training_steps: ${training.n_vqvae_training_steps}
  vqvae_n_embed: 8
  vqvae_embedding_dim: 128
#  vqvae_enc_hidden_dim: 128
  # VQ-BeT
  gpt_block_size: 16
  gpt_input_dim: 72
  gpt_output_dim: 72
  gpt_n_layer: 4
  gpt_n_head: 4
  gpt_hidden_dim: 72
  dropout: 0.1
  mlp_hidden_dim: 144
  offset_loss_weight: 10000.
  primary_code_loss_weight: 5.0
  secondary_code_loss_weight: 0.5
  bet_softmax_temperature: 0.1
  sequentially_select: False
